# .github/workflows/tests.yml
hc
name: Run Python Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        python -m venv env
        source env/bin/activate
        pip install -r requirements.txt

    - name: Run Flask server in background
      run: |
        source env/bin/activate
        nohup python app/main.py &  # Lance le serveur Flask en arrière-plan
        sleep 3  # Donne quelques secondes pour que le serveur démarre

    - name: Run tests
      run: |
        source env/bin/activate
        pytest tests/
